# Copyright (c) 2018 European Organization for Nuclear Research.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""add reaper actions

Revision ID: 748535e3dd22
Revises: a1868275ceb7
Create Date: 2018-10-25 14:01:53.254716

"""

# revision identifiers, used by Alembic.
revision = '748535e3dd22'
down_revision = 'a1868275ceb7'

from alembic import op
import sqlalchemy as sa

from aardvark.db.sqlalchemy import models


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaper_action',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(36), nullable=True),
    sa.Column('state',
              sa.Enum('CANCELED', 'FAILED', 'ONGOING', 'SUCCESS',
                      name='actionstate'),
              nullable=True),
    sa.Column('requested_instances', models.JSONEncodedList(), nullable=True),
    sa.Column('fault_reason', sa.Text(), nullable=True),
    sa.Column('victims', models.JSONEncodedList(), nullable=True),
    sa.Column('event',
              sa.Enum('BUILD_REQUEST', 'REBUILD_REQUEST', 'STATE_CALCULATION',
                      name='actionevent'),
              nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', name='uniq_action0uuid')
    )
    # ### end Alembic commands ###
